# This file was generated by GoReleaser. DO NOT EDIT.
cask "curator" do
  version "0.14.0"

  on_macos do
    on_arm do
      sha256 "9b2914ca024ba7a5a13dbdf4cb535d92ac30bc504562fde6440a3584a4811cd1"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "00ff601092d950f72484905c0cd43cc87855043cc0d128a821d4e7e65eb121f1"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "02d253708d06518edb4cbc9714080df067261074ef94dd6a936471e5e036fc33"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca69ed53f67b2de97f4b42688e94756cd5f2f983b5485f12e8eebbeffa955e53"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_linux_amd64.tar.gz"
    end
  end

  name "curator"
  desc "Agent environment manager"
  homepage "https://github.com/relux-works/curator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "curator"

  # No zap stanza required
end
