# This file was generated by GoReleaser. DO NOT EDIT.
cask "curator" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "28ba80f548913690211134b4f3b077399606431659db35ce621116363a9dd39c"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "052ab30d225408abd1bed72988a006eb9745274014067365964b597b70a1f6ae"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c061dba5c009e4a9e1a2edae03474b98b87d55a78afaac884f43887169611554"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d23bc88d18d5b68e7187892604e9f1e10072a868b539a3380bd462d8804efb8c"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "curator"
  desc "Agent environment manager"
  homepage "https://github.com/relux-works/curator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "curator"

  # No zap stanza required

end
