# This file was generated by GoReleaser. DO NOT EDIT.
cask "curator" do
  version "0.14.0-rc.1"

  on_macos do
    on_intel do
      sha256 "19b0be82a54cfb8837b0bdeda2d29bbb354cc0ae0b66a7f364fd5863ababb1a0"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e61dd2b30eeceecdc4b3876d50617b5505ba18209c6bb8365e4de66e5e5136b"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d5145efd74e7d4a1d511df053532dff94476f06fb518b70f57857610c93fc2d"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2cb247bd5a743806e3558800d6a96c9e4d7f305037475b4f989495d91fb8a559"
      url "https://github.com/relux-works/curator/releases/download/v#{version}/curator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "curator"
  desc "Agent environment manager"
  homepage "https://github.com/relux-works/curator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "curator"

  # No zap stanza required

end
